mongo_uri = "mongodb+srv://grimaldi123:AaSiHiql4ZdHwYEH@deteksi-hama-kol.ojnavgj.mongodb.net/?retryWrites=true&w=majority&appName=deteksi-hama-kol"
mongo_db = "hama_detection"
mongo_collection = "detections"                                 
